name: 'Frontend coverage'
description: 'Compute and publish jest coverage for list of folders'
inputs:
  working-directory:
    description: 'The path to the code that was checkout-ed, relative to $GITHUB_WORKSPACE'
    required: false
    default: '.'
  task:
    description: 'Which step to run (compute, monitor)'
    required: true
    default: 'compute'
  folders-config:
    description: 'JSON config describing the targetted folders'
    required: true
    default: ''
  metric-job-name:
    description: 'Job name of prometheus metrics'
    required: true
    default: ''
  push-gateway-uri:
    description: 'URI of the Prometheus PushGateway'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - run: |
        if [[ "${{ inputs.task }}" == "compute" ]]; then
          cd ${{ inputs.working-directory }}
          $GITHUB_ACTION_PATH/src/compute/coverage-all-folders.js ${{ inputs.folders-config }}
          # $GITHUB_ACTION_PATH/src/compute/coverage-all-folders.js ${{ inputs.folders-config }} | exit $?
        else
          exit 0
        fi
      shell: bash
    - run: |
        if [[ "${{ inputs.task }}" == "monitor" ]]; then
          $GITHUB_ACTION_PATH/src/monitor/push-metrics-all-folders.sh ${{ inputs.metric-job-name }} ${{ inputs.push-gateway-uri }}
          # $GITHUB_ACTION_PATH/src/monitor/push-metrics-all-folders.sh ${{ inputs.metric-job-name }} ${{ inputs.push-gateway-uri }} | exit $?
          echo $? "Out of script"
        else
          exit 0
        fi
        echo $? "Out of if"
      shell: bash