name: "CI"
on: push

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    container:
      image: jobteaser/node:2.0.0
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          path: workspace
      - name: "Install NPM dependencies"
        working-directory: workspace
        run: npm ci
      - name: "Run Jest"
        working-directory: workspace
        run: npm test