name: "CI"
on: push

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    container:
      image: jobteaser/node:2.0.0
      options: --user 1001
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install NPM dependencies"
        run: npm ci
      - name: "Run Jest"
        run: npm test